#!/bin/bash

set -e

EXAMPLES_DIR="./examples"
ROOT_DIR=$(pwd)

for dir in "$EXAMPLES_DIR"/*; do
  if [ -d "$dir" ]; then
    echo "Processing directory: $dir"
    cd "$dir"
    go build .
    go test .
    cd "$ROOT_DIR"
  fi
done
